apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: zj28t0ymw-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: zj28t0ymw-python 
  name: zj28t0ymw-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: zj28t0ymw-python 
